# .github/workflows/comment.yml

name: Comentar si Coverage es Bajo en el Commit

on:
  workflow_run:
    workflows: ["Ejecutar Pruebas y Cobertura"]  # Depende del workflow anterior
    types:
      - completed  # Solo se ejecuta si el workflow de pruebas ha terminado

jobs:
  comment:
    name: Comentar en el Commit si Coverage es Bajo
    runs-on: ubuntu-latest
    if: ${{ failure() && contains(needs.tests.outputs.result, 'failure') }}  # Solo ejecuta si el primer flujo falló

    steps:
      - name: Chequear Código
        uses: actions/checkout@v3

      - name: Comentar en el Commit
        run: |
          echo "La cobertura no cumple el umbral. Reporte:"
          cat coverage.txt  # Imprime el reporte de cobertura

      - name: Crear o Actualizar el Comentario en el Commit
        uses: peter-evans/create-or-update-comment@v3
        with:
          commit-sha: ${{ github.sha }}  # Pone el comentario en el commit directamente
          body: |
            🚨 **Coverage bajo el mínimo requerido (80%)**
            
            El reporte de cobertura es:
            ```
            $(cat coverage.txt)
            ```

