name: Hola Mundo en Commit

on:
  workflow_run:
    workflows: ["Ejecutar Pruebas y Cobertura"]
    types:
      - completed

jobs:
  comment:
    name: Comentar en Commit si Pruebas Fallan
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Crear Comentario en el Commit
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitSha = "${{ github.event.workflow_run.head_sha }}";
            const owner = "${{ github.repository_owner }}";
            const repo = "${{ github.event.workflow_run.repository.name }}";
            const buildUrl = "${{ github.event.workflow_run.html_url }}";  // Link al build fallido
            const failureMessage = "👋 ¡Hola Mundo! Este commit ha fallado en las pruebas. Haz clic [aquí](" + buildUrl + ") para más detalles.";

            // Obtener detalles del fallo (si lo deseas)
            const jobs = await github.rest.actions.listWorkflowJobs({
              owner,
              repo,
              workflow_run_id: github.event.workflow_run.id
            });

            const failedJobs = jobs.data.jobs.filter(job => job.conclusion === 'failure');
            const failedJobNames = failedJobs.map(job => job.name).join(", ");

            // Añadir el mensaje detallado al comentario
            const body = failureMessage + " Los siguientes trabajos fallaron: " + failedJobNames;

            await github.rest.repos.createCommitComment({
              owner,
              repo,
              commit_sha: commitSha,
              body
            });
