# .github/workflows/hola_mundo.yml

name: Hola Mundo en Commit

on:
  workflow_run:
    workflows: ["Ejecutar Pruebas y Cobertura"]
    types:
      - completed

jobs:
  comment:
    name: Comentar en Commit si Pruebas Fallan
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Crear Comentario en el Commit
        uses: actions/github-script@v7
        with:
          script: |
            const commitSha = "${{ github.event.workflow_run.head_sha }}";
            const owner = "${{ github.repository_owner }}";
            const repo = "${{ github.event.workflow_run.repository.name }}";
            const body = "👋 ¡Hola Mundo! Este commit ha fallado en las pruebas.";

            await github.rest.repos.createCommitComment({
              owner,
              repo,
              commit_sha: commitSha,
              body
            });
