# .github/workflows/hola_mundo.yml

name: Hola Mundo

on:
  workflow_run:
    workflows: ["Ejecutar Pruebas y Cobertura"]  # Este es el nombre del primer workflow
    types:
      - completed  # Se ejecuta cuando el workflow anterior termina

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}  # Se ejecuta solo si el flujo anterior falla

    steps:
      - name: Mostrar Hola Mundo
        run: |
          echo "Hola Mundo"
