# .github/workflows/hola_mundo.yml

name: Hola Mundo

on:
  workflow_run:
    workflows: ["Ejecutar Pruebas y Cobertura"]  # El nombre exacto del workflow de test
    types:
      - completed

jobs:
  comment:
    name: Comentar en Commit si Pruebas Fallan
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Crear Comentario en Commit
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.repository.full_name }}
          commit-sha: ${{ github.event.workflow_run.head_sha }}
          body: |
            👋 ¡Hola Mundo! Este commit ha fallado en las pruebas.
