name: Static Analysis (Python)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run_pylint:
    name: Run Pylint on test_calculos.py
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Static Analysis with pylint
        uses: JacobDomagala/StaticAnalysis@master
        with:
          language: Python
          python_dirs: "test_calculos.py"
          pylint_args: "--disable=C0114,C0115,C0116"
